language: node_js
install:
  - npm install
  #- npm install karma-firefox-launcher codeclimate-test-reporter
node_js:
  - '10.11.0'
cache:
  directory:
    - node_module
script:
  - npm run test
after_success:
 - travis_wait npm run coveralls
env:
  - NODE_ENV=test
addons:
  code_climate:
    repo_token: 53becf6d724ff4125ae096a29e896849f42920e5a83cfc283e383d0bf4799796
